In [1]:
import pandas as pd
import  numpy as np

## 1.1 Dataframe for array

In [7]:
# creating a array
data = np.array([[1,4],[2,5],[3,6]])

In [10]:
df = pd.DataFrame(data,index=['row1','row2','row3'],
                  columns=['col1','col2'])
## pay attention to the D and F ! Upper!

In [11]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

## 1.2 Dataframe for Dictionary

In [12]:
meat = ['Beaf','Duck','Chicker','Lamb']
taste =['Nice','Good','Not bad','Good']

In [13]:
dict_meat={'Meat':meat,'Taste':taste}

In [16]:
df=pd.DataFrame(dict_meat,index=['Food1','Food2','Food3','Food4'])

In [17]:
df

          Meat    Taste
Food1     Beaf     Nice
Food2     Duck     Good
Food3  Chicker  Not bad
Food4     Lamb     Good

In [4]:
data = {
    'OrderID': [101, 102, 103, 104, 105],
    'Product': ['Latte', 'Americano', 'Cappuccino', 'Latte', 'Mocha'],
    'Price': [32, 25, 30, 32, 35],
    'Quantity': [2, 1, 3, 1, 2],
    'Date': ['2023-10-01', '2023-10-01', '2023-10-02', '2023-10-02', '2023-10-03']
}

In [7]:
df_sample = pd.DataFrame(data)

In [8]:
df_sample.to_csv('coffee_sales.csv', index=False)
print("CSV 文件已生成！快去文件夹里找找看。")

CSV 文件已生成！快去文件夹里找找看。

In [2]:
df_eg = pd.read_csv("coffee_sales.csv")

In [3]:
# Reading the table
# 这里的head表示显示前n行，默认为5，当数据量极大的时候有用。对应的，也可以tail(n)看尾部
df_eg.head()

   OrderID     Product  Price  Quantity        Date
0      101       Latte     32         2  2023-10-01
1      102   Americano     25         1  2023-10-01
2      103  Cappuccino     30         3  2023-10-02
3      104       Latte     32         1  2023-10-02
4      105       Mocha     35         2  2023-10-03

In [12]:
# Show in rows
pd.set_option('Display.max_rows',4)
df_eg

    OrderID    Product  Price  Quantity        Date
0       101      Latte     32         2  2023-10-01
1       102  Americano     25         1  2023-10-01
..      ...        ...    ...       ...         ...
3       104      Latte     32         1  2023-10-02
4       105      Mocha     35         2  2023-10-03

[5 rows x 5 columns]

## 2.Attributes

In [17]:
df_eg.shape

(5, 5)

In [18]:
df_eg.index

RangeIndex(start=0, stop=5, step=1)

In [19]:
df_eg.columns

Index(['OrderID', 'Product', 'Price', 'Quantity', 'Date'], dtype='str')

In [20]:
df_eg.dtypes

OrderID     int64
Product       str
            ...
Quantity    int64
Date          str
Length: 5, dtype: object

In [21]:
df_eg.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   5 non-null      int64
 1   Product   5 non-null      str
 2   Price     5 non-null      int64
 3   Quantity  5 non-null      int64
 4   Date      5 non-null      str
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

In [22]:
df_eg.describe()

       OrderID  Price  Quantity
count      5.0    5.0       5.0
mean     103.0   30.8       1.8
...        ...    ...       ...
75%      104.0   32.0       2.0
max      105.0   35.0       3.0

[8 rows x 3 columns]

## 3 Some Functions

In [23]:
len(df_eg)

5

In [27]:
#max(df_eg) min also works
max(df_eg.index)

4

In [4]:
round(df_eg,2)

   OrderID     Product  Price  Quantity        Date
0      101       Latte     32         2  2023-10-01
1      102   Americano     25         1  2023-10-01
2      103  Cappuccino     30         3  2023-10-02
3      104       Latte     32         1  2023-10-02
4      105       Mocha     35         2  2023-10-03

In [5]:
df_eg['Price']

0    32
1    25
2    30
3    32
4    35
Name: Price, dtype: int64

In [6]:
type(df_eg['Price'])

pandas.Series

In [8]:
df_eg['Price'].index
df_eg['Price'].head(3)

0    32
1    25
2    30
Name: Price, dtype: int64

In [12]:
df_eg[['Product','Price']]

      Product  Price
0       Latte     32
1   Americano     25
2  Cappuccino     30
3       Latte     32
4       Mocha     35

## 4 **Adding new element**

In [14]:
df_eg['population']=114514
df_eg

   OrderID     Product  Price  Quantity        Date  population
0      101       Latte     32         2  2023-10-01      114514
1      102   Americano     25         1  2023-10-01      114514
2      103  Cappuccino     30         3  2023-10-02      114514
3      104       Latte     32         1  2023-10-02      114514
4      105       Mocha     35         2  2023-10-03      114514

### **Using Array**

In [15]:
import numpy as np

In [17]:
mild_score = np.arange(0,5)

In [18]:
df_eg['mild_score']=mild_score
df_eg

   OrderID     Product  Price  Quantity        Date  population  mild_score
0      101       Latte     32         2  2023-10-01      114514           0
1      102   Americano     25         1  2023-10-01      114514           1
2      103  Cappuccino     30         3  2023-10-02      114514           2
3      104       Latte     32         1  2023-10-02      114514           3
4      105       Mocha     35         2  2023-10-03      114514           4

In [19]:
int_mild_score =np.random.randint(1,1000,size=5)
df_eg['mild_score'] = int_mild_score
df_eg

   OrderID     Product  Price  Quantity        Date  population  mild_score
0      101       Latte     32         2  2023-10-01      114514         794
1      102   Americano     25         1  2023-10-01      114514          84
2      103  Cappuccino     30         3  2023-10-02      114514         301
3      104       Latte     32         1  2023-10-02      114514         919
4      105       Mocha     35         2  2023-10-03      114514         303

In [20]:
np.random.uniform(1,1000,size=8)

array([689.87776162, 727.72658126, 735.74505002, 547.55220402,
       155.24602765, 188.95072755, 536.98967678, 585.75374736])

### 4.1 Adding columns

#### 4.1.1 **Assign()**

In [25]:
import numpy as np
import pandas as pd

In [39]:
score1 =np.random.randint(1,1000,size=5)
score2 =np.random.randint(1,1000,size=5)

In [40]:
series1 =pd.Series(score1,index=np.arange(0,5))
series2 =pd.Series(score1,index=np.arange(0,5))
series1

0    721
1    476
2    915
3    981
4     70
dtype: int32

In [41]:
df_eg= df_eg.assign(score1 = series1,score2=series2)

In [42]:
df_eg #记得赋值一下，不然不会修改原表格

,OrderID,Product,Price,Quantity,Date,population,mild_score,score1,score2
0,101,Latte,32,2,2023-10-01,114514,794,721,721
1,102,Americano,25,1,2023-10-01,114514,84,476,476
2,103,Cappuccino,30,3,2023-10-02,114514,301,915,915
3,104,Latte,32,1,2023-10-02,114514,919,981,981
4,105,Mocha,35,2,2023-10-03,114514,303,70,70

#### 4.1.2 **Insert()**

In [43]:
df_eg.insert(2,'Position',series1)
df_eg

,OrderID,Product,Position,Price,Quantity,Date,population,mild_score,score1,score2
0,101,Latte,721,32,2,2023-10-01,114514,794,721,721
1,102,Americano,476,25,1,2023-10-01,114514,84,476,476
2,103,Cappuccino,915,30,3,2023-10-02,114514,301,915,915
3,104,Latte,981,32,1,2023-10-02,114514,919,981,981
4,105,Mocha,70,35,2,2023-10-03,114514,303,70,70