## 4.2 **Math Operation()**

#### 4.2.1 **Operations in columns**

In [1]:
from random import random

import pandas as pd
import numpy as np

# 构造一个模拟咖啡馆的业务数据
data = {
    'Item': ['Latte', 'Americano', 'Cappuccino', 'Mocha', 'Matcha', 'Cold Brew'],
    'Unit_Price': [32.0, 25.0, 30.0, 35.0, 38.0, 28.0],     # 单价 (float)
    'Quantity': [10, 15, 8, 12, 0, 20],                    # 销量 (int)
    'Cost_Per_Cup': [12.5, 8.0, 11.0, 14.0, 15.0, 9.0],    # 每杯成本 (float)
    'Discount_Rate': [0.9, 1.0, 0.85, 1.0, 0.9, 0.95],     # 折扣率 (0.9表示9折)
    'Rating': [4.8, 4.5, 4.2, 4.9, np.nan, 4.7]            # 顾客评分 (带有一个NaN空值)
}

df_cafe = pd.DataFrame(data)
print("--- AI 咖啡馆经营简表 ---")
print(df_cafe)

--- AI 咖啡馆经营简表 ---
         Item  Unit_Price  Quantity  Cost_Per_Cup  Discount_Rate  Rating
0       Latte        32.0        10          12.5           0.90     4.8
1   Americano        25.0        15           8.0           1.00     4.5
2  Cappuccino        30.0         8          11.0           0.85     4.2
3       Mocha        35.0        12          14.0           1.00     4.9
4      Matcha        38.0         0          15.0           0.90     NaN
5   Cold Brew        28.0        20           9.0           0.95     4.7

In [22]:
df_cafe['Quantity'].sum()

np.int64(65)

In [25]:
df_cafe['Quantity'].count()
df_cafe['Quantity'].mean()
df_cafe['Quantity'].std()# std 是标准差的意思，衡量波动，和方差一个样
df_cafe['Quantity'].max()
df_cafe['Quantity'].min()

np.int64(0)

In [23]:
df_cafe.describe()
#一个函数抵得上上面的所有

       Unit_Price   Quantity  Cost_Per_Cup  Discount_Rate    Rating
count    6.000000   6.000000      6.000000       6.000000  5.000000
mean    31.333333  10.833333     11.583333       0.933333  4.620000
std      4.718757   6.765107      2.764356       0.060553  0.277489
min     25.000000   0.000000      8.000000       0.850000  4.200000
25%     28.500000   8.500000      9.500000       0.900000  4.500000
50%     31.000000  11.000000     11.750000       0.925000  4.700000
75%     34.250000  14.250000     13.625000       0.987500  4.800000
max     38.000000  20.000000     15.000000       1.000000  4.900000

#### 4.2.2 **Operations in row**

In [5]:
df_cafe

         Item  Unit_Price  Quantity  Cost_Per_Cup  Discount_Rate  Rating
0       Latte        32.0        10          12.5           0.90     4.8
1   Americano        25.0        15           8.0           1.00     4.5
2  Cappuccino        30.0         8          11.0           0.85     4.2
3       Mocha        35.0        12          14.0           1.00     4.9
4      Matcha        38.0         0          15.0           0.90     NaN
5   Cold Brew        28.0        20           9.0           0.95     4.7

In [28]:
df_cafe['Unit_Price']+df_cafe['Quantity']+df_cafe['Cost_Per_Cup']

0    54.5
1    48.0
2    49.0
3    61.0
4    53.0
5    57.0
dtype: float64

In [31]:
df_cafe['Raw_Revenue'] = df_cafe['Unit_Price'] * df_cafe['Quantity']
df_cafe.round(2)#这是保留n为小数

,Item,Unit_Price,Quantity,Cost_Per_Cup,Discount_Rate,Rating,Raw_Revenue
0,Latte,32.0,10,12.5,0.90,4.8,320.0
1,Americano,25.0,15,8.0,1.00,4.5,375.0
2,Cappuccino,30.0,8,11.0,0.85,4.2,240.0
3,Mocha,35.0,12,14.0,1.00,4.9,420.0
4,Matcha,38.0,0,15.0,0.90,NaN,0.0
5,Cold Brew,28.0,20,9.0,0.95,4.7,560.0

In [35]:
df_cafe['Rating'].value_counts(normalize=True)#前者返回出现次数，后者若等于True返回百分比

Rating
4.8    0.2
4.5    0.2
4.2    0.2
4.9    0.2
4.7    0.2
Name: proportion, dtype: float64

#### 4.3 **Sort Operation()**

In [45]:
df_cafe.sort_values(['Rating','Quantity'],ascending=False,inplace=True)
df_cafe

,Item,Unit_Price,Quantity,Cost_Per_Cup,Discount_Rate,Rating,Raw_Revenue
3,Mocha,35.0,12,14.0,1.00,4.9,420.0
0,Latte,32.0,10,12.5,0.90,4.8,320.0
5,Cold Brew,28.0,20,9.0,0.95,4.7,560.0
1,Americano,25.0,15,8.0,1.00,4.5,375.0
2,Cappuccino,30.0,8,11.0,0.85,4.2,240.0
4,Matcha,38.0,0,15.0,0.90,NaN,0.0

In [44]:
df_cafe.sort_values(['Item'],ascending=False,inplace=False,key = lambda col:col.str.lower())
df_cafe

,Item,Unit_Price,Quantity,Cost_Per_Cup,Discount_Rate,Rating,Raw_Revenue
3,Mocha,35.0,12,14.0,1.00,4.9,420.0
4,Matcha,38.0,0,15.0,0.90,NaN,0.0
0,Latte,32.0,10,12.5,0.90,4.8,320.0
5,Cold Brew,28.0,20,9.0,0.95,4.7,560.0
2,Cappuccino,30.0,8,11.0,0.85,4.2,240.0
1,Americano,25.0,15,8.0,1.00,4.5,375.0

#### 4.3.2 ***Sort_Index***

In [54]:
new_index = np.arange(0,6)

In [55]:
np.random.shuffle(new_index)
df_cafe['new_index']=new_index
df_cafe

,Item,Unit_Price,Quantity,Cost_Per_Cup,Discount_Rate,Rating,Raw_Revenue,new_index
3,Mocha,35.0,12,14.0,1.00,4.9,420.0,5
0,Latte,32.0,10,12.5,0.90,4.8,320.0,2
5,Cold Brew,28.0,20,9.0,0.95,4.7,560.0,1
1,Americano,25.0,15,8.0,1.00,4.5,375.0,0
2,Cappuccino,30.0,8,11.0,0.85,4.2,240.0,4
4,Matcha,38.0,0,15.0,0.90,NaN,0.0,3

In [11]:
df_cafe.sort_index(ascending=False,inplace=False)

         Item  Unit_Price  Quantity  Cost_Per_Cup  Discount_Rate  Rating
5   Cold Brew        28.0        20           9.0           0.95     4.7
4      Matcha        38.0         0          15.0           0.90     NaN
3       Mocha        35.0        12          14.0           1.00     4.9
2  Cappuccino        30.0         8          11.0           0.85     4.2
1   Americano        25.0        15           8.0           1.00     4.5
0       Latte        32.0        10          12.5           0.90     4.8

In [13]:
df_cafe.set_index('Quantity',inplace=False)  #这是把某一列作为index

                Item  Unit_Price  Cost_Per_Cup  Discount_Rate  Rating
Quantity
10             Latte        32.0          12.5           0.90     4.8
15         Americano        25.0           8.0           1.00     4.5
8         Cappuccino        30.0          11.0           0.85     4.2
12             Mocha        35.0          14.0           1.00     4.9
0             Matcha        38.0          15.0           0.90     NaN
20         Cold Brew        28.0           9.0           0.95     4.7

#### 4.4 **Rename a column**

In [5]:
df_cafe=df_cafe.rename(columns={'Unit_Price':'Price','Cost_Per_Cup':'Cost','Discount_Rate':'Rate'})

In [7]:
df_cafe=df_cafe.rename(index={0:'A',1:'B',2:'C'})

In [8]:
df_cafe

         Item  Price  Quantity  Cost  Rate  Rating
A       Latte   32.0        10  12.5  0.90     4.8
B   Americano   25.0        15   8.0  1.00     4.5
C  Cappuccino   30.0         8  11.0  0.85     4.2
3       Mocha   35.0        12  14.0  1.00     4.9
4      Matcha   38.0         0  15.0  0.90     NaN
5   Cold Brew   28.0        20   9.0  0.95     4.7